services:
  aero-defense:
    build: .
    container_name: ita_project_we_can_fly
    volumes:
      - .:/app # Mount current dir to save charts/logs back to host
    command: python standalone_sim.py
